### ISSUE TITLE
ERR_HTTP_HEADERS_SENT with users/login api

### ISSUE THREAD

**Issue by jenho-webdev** [jenho-webdev/TuneStack#19]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (C:\Users\jenny\Documents\Github\TuneStack\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (C:\Users\jenny\Documents\Github\TuneStack\node_modules\express\lib\response.js:174:12)
    at done (C:\Users\jenny\Documents\Github\TuneStack\node_modules\express\lib\response.js:1035:10)
    at ExpressHandlebars.<anonymous> (C:\Users\jenny\Documents\Github\TuneStack\node_modules\express-handlebars\dist\express-handlebars.js:210:17)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jenny\Documents\Github\TuneStack\node_modules\express-handlebars\dist\express-handlebars.js:10:58)

**Comment by jenho-webdev** [comment]
#24
